java_library(
    name = "utils",
    srcs = [
        "AssertUtils.java",
        "ParseUtils.java",
        "ProtoUtils.java",
        "ReflectionUtils.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//java/com/onecodelabs/database:constants",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_protobuf_protobuf_java",
    ],
)
