load("//bzl:common.bzl", "js2proto", "json2proto")

java_library(
    name = "Json2Proto",
    srcs = ["Json2Proto.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//java/com/onecodelabs/common:utils",
        "//java/com/onecodelabs/flags",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_protobuf_protobuf_java_util",
    ],
)
