package(
    default_visibility = ["//java/com/onecodelabs/serverframework/example:__subpackages__"],
)

java_library(
    name = "actions",
    srcs = [
        "CreateBlogAction.java",
        "GetBlogAction.java",
        "ListBlogsAction.java",
    ],
    deps = [
        "//java/com/onecodelabs/serverframework/example:blog_service_java_proto",
        "//java/com/onecodelabs/serverframework/request",
    ],
)
