# proto-file: database/schema.proto
# proto-message: Schema

proto_import: "com.onecodelabs.database.Car"

table: {
  name: "Cars"
  column: {
    name: "Car"
    type: "com.onecodelabs.database.Car"
  }
  primary_key: {
    column_name: "Car"
    field_name: "id"
  }
}