load("@rules_java//java:defs.bzl", "java_binary", "java_library", "java_test")

java_test(
    name = "HelloWorldTest",
    srcs = ["HelloWorldTest.java"],
    deps = ["//java/com/onecodelabs/helloworld:helloworld_library"],
)
